"""Constantes de layout para janela 1280x720."""

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_TITLE = "RPG Turno - Battle Preview"
FPS = 60

# Battlefield area (top portion)
BATTLEFIELD_Y = 40
BATTLEFIELD_HEIGHT = 440

# Enemy area (left side)
ENEMY_AREA_X = 60
ENEMY_FRONT_X = 280
ENEMY_BACK_X = 60
ENEMY_START_Y = 60

# Party area (right side)
PARTY_AREA_X = 800
PARTY_FRONT_X = 800
PARTY_BACK_X = 1060
PARTY_START_Y = 60

# Character card dimensions
CARD_WIDTH = 160
CARD_HEIGHT = 130
CARD_SPACING_Y = 145
BAR_WIDTH = 130
BAR_HEIGHT = 10

# Combat log panel (bottom)
LOG_PANEL_X = 10
LOG_PANEL_Y = 500
LOG_PANEL_WIDTH = 1260
LOG_PANEL_HEIGHT = 210
LOG_LINE_HEIGHT = 22
LOG_MAX_VISIBLE = 9

# Round indicator (top center)
ROUND_INDICATOR_X = 540
ROUND_INDICATOR_Y = 8

# Action panel (left side of bottom area, interactive mode)
ACTION_PANEL_X = 10
ACTION_PANEL_Y = 500
ACTION_PANEL_WIDTH = 400
ACTION_PANEL_HEIGHT = 210
ACTION_LINE_HEIGHT = 24

# Economy bar (above action panel)
ECONOMY_BAR_X = 10
ECONOMY_BAR_Y = 472
ECONOMY_BAR_HEIGHT = 22
ECONOMY_SLOT_WIDTH = 80
ECONOMY_SLOT_SPACING = 6

# Turn indicator
TURN_INDICATOR_BORDER = 3
TURN_INDICATOR_PULSE_SPEED = 4.0

# Event pacing
EVENT_DELAY_MS = 1500
ROUND_FLASH_MS = 800
